const translations = {
    en: { greeting: 'Welcome Back', title: 'Sign In', subtitle: 'Enter your credentials to access your DreamHome account', emailLabel: 'Email Address', passwordLabel: 'Password', forgot: 'Forgot password?', emailPlaceholder: 'you@example.com', passPlaceholder: '••••••••', remember: 'Remember me', submit: 'Sign In to DreamHome', registerText: "Don't have an account?", registerLink: 'Create one free', emailError: 'Invalid email format', passError: 'Password must be at least 6 characters', loginError: 'Invalid email or password. Please try again.', toastSuccess: 'Welcome back to DreamHome!', socialGoogle: 'Google', socialApple: 'Apple', dividerText: 'or continue with email' },
    ar: { greeting: 'مرحباً بعودتك', title: 'تسجيل الدخول', subtitle: 'أدخل بياناتك للوصول إلى حساب بيت الأحلام', emailLabel: 'البريد الإلكتروني', passwordLabel: 'كلمة المرور', forgot: 'نسيت كلمة المرور؟', emailPlaceholder: 'name@example.com', passPlaceholder: '••••••••', remember: 'تذكرني', submit: 'تسجيل الدخول إلى بيت الأحلام', registerText: 'ليس لديك حساب؟', registerLink: 'أنشئ حساباً مجاناً', emailError: 'صيغة البريد الإلكتروني غير صحيحة', passError: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل', loginError: 'البريد الإلكتروني أو كلمة المرور غير صحيحة', toastSuccess: 'مرحباً بعودتك إلى بيت الأحلام!', socialGoogle: 'جوجل', socialApple: 'آبل', dividerText: 'أو تابع بالبريد الإلكتروني' }
};

let currentLang = 'en';
const emailField = document.getElementById('emailField');
const passField = document.getElementById('passField');
const emailErr = document.getElementById('emailErr');
const passErr = document.getElementById('passErr');
const submitBtn = document.getElementById('submitBtn');
const toast = document.getElementById('toast');
const toastMsg = document.getElementById('toastMsg');
const checkBox = document.getElementById('checkBox');

function applyTranslations(lang) { const t = translations[lang]; if (!t) return; const greetingEl = document.querySelector('.greeting-text'); if (greetingEl) greetingEl.textContent = t.greeting; const titleEl = document.querySelector('.form-title'); if (titleEl) titleEl.textContent = t.title; const subtitleEl = document.querySelector('.form-subtitle'); if (subtitleEl) subtitleEl.textContent = t.subtitle; const labels = document.querySelectorAll('.input-label span'); if (labels[0]) labels[0].textContent = t.emailLabel; if (labels[1]) labels[1].textContent = t.passwordLabel; const forgotLink = document.querySelector('.forgot-link'); if (forgotLink) forgotLink.textContent = t.forgot; if (emailField) emailField.placeholder = t.emailPlaceholder; if (passField) passField.placeholder = t.passPlaceholder; const checkboxLabel = document.querySelector('.checkbox-label'); if (checkboxLabel) checkboxLabel.textContent = t.remember; if (submitBtn) submitBtn.textContent = t.submit; const registerSpan = document.querySelector('.register-row span:first-child'); if (registerSpan) registerSpan.textContent = t.registerText; const registerLink = document.querySelector('.register-link'); if (registerLink) registerLink.textContent = t.registerLink; if (emailErr) emailErr.textContent = t.emailError; if (passErr) passErr.textContent = t.passError; const socialBtns = document.querySelectorAll('.social-btn'); if (socialBtns[0]) socialBtns[0].innerHTML = `<i class="fab fa-google social-icon"></i> ${t.socialGoogle}`; if (socialBtns[1]) socialBtns[1].innerHTML = `<i class="fab fa-apple social-icon"></i> ${t.socialApple}`; const dividerSpan = document.querySelector('.divider-text'); if (dividerSpan) dividerSpan.textContent = t.dividerText; }

function setLanguage(lang) { currentLang = lang; document.body.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr'); document.documentElement.lang = lang; document.querySelectorAll('.lang-btn').forEach(btn => { if (btn.getAttribute('data-lang') === lang) btn.classList.add('active'); else btn.classList.remove('active'); }); applyTranslations(lang); localStorage.setItem('dreamhome_lang', lang); }

function togglePassword() { if (!passField) return; const type = passField.type === 'password' ? 'text' : 'password'; passField.type = type; const eyeIcon = document.getElementById('eyeIcon'); if (eyeIcon) eyeIcon.classList.toggle('fa-eye'), eyeIcon.classList.toggle('fa-eye-slash'); }
function toggleCheckbox() { if (checkBox) checkBox.classList.toggle('checked'); }
function clearError(fieldId, errorId) { const field = document.getElementById(fieldId); const error = document.getElementById(errorId); if (field) field.classList.remove('error'); if (error) error.classList.remove('show'); }
function showError(fieldId, errorId, customMessage = null) { const field = document.getElementById(fieldId); const error = document.getElementById(errorId); if (field) field.classList.add('error'); if (error) { if (customMessage) error.textContent = customMessage; error.classList.add('show'); } }
function showToast(message, isError = false) { if (toastMsg) toastMsg.textContent = message; const toastIcon = toast ? toast.querySelector('.toast-icon i') : null; if (toastIcon) { if (isError) { toastIcon.className = 'fas fa-exclamation-circle'; toast.style.borderLeftColor = '#e07a5f'; } else { toastIcon.className = 'fas fa-check-circle'; toast.style.borderLeftColor = '#c9a96e'; } } if (toast) { toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3000); } }
function validateEmailOnInput() { if (!emailField) return; const email = emailField.value.trim(); if (email.length === 0) { clearError('emailField', 'emailErr'); return; } const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/; if (!emailRegex.test(email)) showError('emailField', 'emailErr'); else clearError('emailField', 'emailErr'); }
function validateForm() { if (!emailField || !passField) return false; const email = emailField.value.trim(); const password = passField.value; let isValid = true; const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/; if (!email || !emailRegex.test(email)) { showError('emailField', 'emailErr'); isValid = false; } else clearError('emailField', 'emailErr'); if (!password || password.length < 6) { showError('passField', 'passErr'); isValid = false; } else clearError('passField', 'passErr'); return isValid; }
function handleLogin() { if (!validateForm()) return; const email = emailField.value.trim(); const password = passField.value; const rememberMe = checkBox ? checkBox.classList.contains('checked') : false; const originalText = submitBtn ? submitBtn.textContent : ''; if (submitBtn) { submitBtn.classList.add('loading'); submitBtn.innerHTML = '&nbsp;'; } fetch('login.php', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: email, password: password }) }).then(response => response.json()).then(data => { if (submitBtn) { submitBtn.classList.remove('loading'); submitBtn.innerHTML = originalText; } if (data.success) { const sessionData = { id: data.user.id, email: data.user.email, name: data.user.name, first_name: data.user.first_name, last_name: data.user.last_name, phone: data.user.phone, city: data.user.city, role: data.user.role || 'tenant', loggedInAt: new Date().toISOString() }; if (rememberMe) localStorage.setItem('dreamhome_session', JSON.stringify(sessionData)); else sessionStorage.setItem('dreamhome_session', JSON.stringify(sessionData)); showToast(`Welcome back ${data.user.name}! Redirecting...`); setTimeout(() => window.location.href = 'index.php', 1500); } else showToast(data.message, true); }).catch(error => { if (submitBtn) { submitBtn.classList.remove('loading'); submitBtn.innerHTML = originalText; } showToast('Connection error. Please try again.', true); }); }
function socialLogin(provider) { const btn = event.currentTarget; btn.style.opacity = '0.6'; btn.style.pointerEvents = 'none'; setTimeout(() => { btn.style.opacity = ''; btn.style.pointerEvents = ''; const sessionData = { email: `${provider.toLowerCase()}@dreamhome.com`, name: provider, role: 'user', loggedInAt: new Date().toISOString(), socialLogin: true }; sessionStorage.setItem('dreamhome_session', JSON.stringify(sessionData)); showToast(`Logged in with ${provider}`); setTimeout(() => window.location.href = 'index.php', 1200); }, 800); }

document.addEventListener('DOMContentLoaded', () => { const savedLang = localStorage.getItem('dreamhome_lang'); setLanguage(savedLang && (savedLang === 'en' || savedLang === 'ar') ? savedLang : 'en'); if (emailField) { emailField.addEventListener('input', validateEmailOnInput); emailField.addEventListener('keypress', (e) => { if (e.key === 'Enter') handleLogin(); }); } if (passField) passField.addEventListener('keypress', (e) => { if (e.key === 'Enter') handleLogin(); }); });

window.setLanguage = setLanguage;
window.togglePassword = togglePassword;
window.toggleCheckbox = toggleCheckbox;
window.handleLogin = handleLogin;
window.socialLogin = socialLogin;